docs/api-reference/api-price.mdx, docs/docs.json
=> Add API price docs

src/llm/__init__.py, src/llm/plugins/deepseek_llm.py, src/llm/plugins/gemini_llm.py, src/llm/plugins/openai_llm.py, tests/llm/plugins/test_deepseek_llm.py, tests/llm/plugins/test_gemini_llm.py, tests/llm/plugins/test_openmind_llm.py, tests/llm/test_init.py, tests/llm/test_llm_plugins.py
- Allow users to configure models in the config file
- Change the default model of the open ai to 4o-mini. The response time is around 1.2 seconds.
=> Support multiple models

.gitignore, README.md
This fix adds some necessary requirements to the README file and makes the project more clear!
=> fix: Change README 

config/conversation.json, config/cubly.json, config/iris.json, config/robot_wallet_safe.json, docs/api-reference/api-price.mdx, docs/docs.json, pyproject.toml, src/actions/speak/connector/elevenlabs_tts.py, src/actions/speak/connector/riva_tts.py, src/inputs/plugins/asr.py, src/inputs/plugins/vlm_cloud.py, src/llm/plugins/luna_llm.py, src/providers/elevenlabs_tts_provider.py, src/providers/riva_tts_provider.py, tests/providers/test_elevenlabs_tts_provider copy.py, tests/providers/test_riva_tts_provider.py, tests/providers/test_tts_provider.py, uv.lock
=> Support ElevenLabs TTS

config/conversation.json, config/cubly.json, config/deepseek.json, config/gemini.json, config/iris.json, config/robot_wallet_safe.json, config/spot.json, config/twitter.json, config/unitree.json, docs/development/guide.mdx, src/runtime/config.py, tests/runtime/test_config.py
=> Add global API key support to runtime configuration

docs/docs.json
Documentation theme color update to be same as the SaaS portal.
=> Change documentation theme color to be same as the SaaS portal.

config/conversation.json, src/actions/emotion/connector/unitree_sdk.py, src/fuser/__init__.py, src/inputs/plugins/asr.py, src/inputs/plugins/ethereum_governance.py, src/inputs/plugins/unitree_g1_basic.py, src/inputs/plugins/unitree_g1_camera_vlm_cloud.py, src/inputs/plugins/unitree_go2_camera_vlm_cloud.py, src/inputs/plugins/vlm_cloud.py, src/inputs/plugins/vlm_coco_local.py, src/inputs/plugins/vlm_dummy_local.py, src/llm/__init__.py, src/llm/plugins/deepseek_llm.py, src/llm/plugins/gemini_llm.py, src/llm/plugins/openai_llm.py, src/providers/llm_history_manager.py, src/runtime/config.py, src/runtime/robotics.py
=> Add LLMHistoryManager

src/providers/elevenlabs_tts_provider.py
Fix TTS from ElevenLabs
- Increase chunk size
- Avoid to open the stream twice
=> Fix TTS from ElevenLabs

config/conversation.json, config/iris.json, src/actions/emotion/connector/unitree_sdk.py, src/fuser/__init__.py, src/inputs/plugins/asr.py, src/inputs/plugins/ethereum_governance.py, src/inputs/plugins/unitree_g1_basic.py, src/inputs/plugins/unitree_g1_camera_vlm_cloud.py, src/inputs/plugins/unitree_go2_camera_vlm_cloud.py, src/inputs/plugins/vlm_cloud.py, src/inputs/plugins/vlm_coco_local.py, src/inputs/plugins/vlm_dummy_local.py, src/llm/__init__.py, src/llm/plugins/deepseek_llm.py, src/llm/plugins/gemini_llm.py, src/llm/plugins/openai_llm.py, src/providers/llm_history_manager.py, src/runtime/config.py, src/runtime/robotics.py
=> history block synthesis

src/inputs/plugins/asr.py, tests/inputs/base/test_asr.py
For the ASR response, we only keep the result with more than one word
- Add filter for the ASR response
=> Filter invalid ASR response

docs/robotics/unitree_humanoid.mdx, src/providers/elevenlabs_tts_provider.py
Add docs to set the default devices
=> Add docs to set default devices

src/actions/move_safe/connector/ros2.py, src/providers/elevenlabs_tts_provider.py
[WIP] You can use RT and LT keys to rotate the robotics and d-pad to move the robotics
=> Unitree Go2 xbox controller

config/conversation.json, config/cubly.json, config/robot_wallet_safe.json, config/unitree_g1_iris.json, config/unitree_go2.json, src/inputs/plugins/google_asr.py, src/inputs/plugins/riva_asr.py, tests/inputs/base/test_riva_asr.py
Add Google ASR
Support Google ASR
=> Add google asr

config/unitree_go2.json, docs/robotics/unitree_go2_quadruped.mdx, src/actions/move_safe/connector/ros2.py, src/inputs/plugins/google_asr.py, src/inputs/plugins/riva_asr.py, src/inputs/plugins/unitree_go2_rt_lowstate.py, src/inputs/plugins/vlm_dummy_local.py, src/inputs/plugins/vlm_gemini.py, src/inputs/plugins/vlm_openai.py, src/inputs/plugins/vlm_vila.py, src/llm/plugins/openai_llm.py, src/runtime/cortex.py, system_hw_test/go2_camera_opencv.py, system_hw_test/go2_capture_image.py, system_hw_test/go2_data_stream.py, system_hw_test/go2_lidar.py, uv.lock
Overall smoothing and testing of Bits, plus a new system to tell her is she is standing or sitting.
=> add attitude message

README.md, docs/docs.json, docs/robotics/unitree_g1_humanoid.mdx, docs/robotics/unitree_go2_quadruped.mdx
update README to add 2 links.
re-org the docs nav tree 
rename unitree files title
=> update README and reorganize the nav for docs

pyproject.toml, system_hw_test/turtlebot4_keyboard_movement.py, uv.lock
Add TurtleBot4 keyboard movement examples
=> Add turtlebot4 keyboard movement

docs/docs.json, docs/getting-started/architecture.mdx, docs/getting-started/gazebo.mdx, docs/home.mdx
- fix tutorials broken links
- typo for architecture page
- move gazebo sim to tutorials
- add turtlebot4 in the nav and home page
- remove the duplicate architecture page in nav
=> fix docs broken links and refine the structures

CONTRIBUTING.md, README.md
=> refine README and add CONTRIBUTING

system_hw_test/turtlebot_zenoh/docker-compose.yaml
Add maximum logs for TurtleBot zenoh bridge
=> Add maximum logs

config/turtlebot4.json5, docs/robotics/turtlebot4_zenoh.mdx
=> improve TB4 VLM stability behaviors

docs/docs.json, docs/robotics/tesla_dimo.mdx, docs/robotics/turtlebot4_zenoh.mdx
Add steps to the docs for setting up the DIMO connection.
=> Update Tesla DIMO docs

config/turtlebot4.json5, docs/robotics/turtlebot4_zenoh.mdx, src/actions/move_turtle/connector/zenoh.py, src/actions/move_turtle/interface.py, src/inputs/plugins/turtlebot4_lidar_batt_hazard.py, src/llm/plugins/openai_llm.py, src/runtime/cortex.py, system_hw_test/turtlebot_zenoh/config_create3.json5
=> TB4 optimization

system_hw_test/turtlebot_zenoh/config_create3.json5, system_hw_test/turtlebot_zenoh/config_rpi.json5
Enable more topics and services
=> Update bridge topics

docs/docs.json, docs/getting-started/faq.mdx
=> add FAQ page

pyproject.toml, src/inputs/plugins/google_asr.py, src/providers/asr_provider.py
Add support for different languages for Google ASR
Update Google ASR input plugin and provider to allow for user-specified languages for ASR.
=> Add support for different languages for Google ASR

README.md, docs/getting-started/get-started.mdx
remove the detailed steps for installation in README
all is in docs.
=> move installation from README to docs

system_hw_test/gps_mag/gps_mag.ino
=> New calibration case for raspberry module

docs/docs.json
=> add gps link for doc

docs/api-reference/endpoints/llm_agent.mdx, docs/api-reference/openapi.yml, docs/docs.json, src/llm/plugins/multi_llm.py, tests/llm/plugins/test_multi_llm.py
Update multi-agent output structure and add docs
=> Update multi-agent output structure and add docs

src/inputs/plugins/turtlebot4_lidar_batt_hazard.py, tests/actions/test_base.py, tests/inputs/base/test_unitree_camera_vlm_provider.py
Fix the warnings of the unit tests
=> Fix warning of unit tests

config/fabric_gps.json5, src/actions/move_to_peer/connector/ros2.py, src/actions/move_to_peer/interface.py
=> Move to peer action

src/providers/rplidar_provider.py
Add properties to read the data from the rplidar_provider
=> Add property to read the data

docs/api-reference/openapi.yml
update multi-agent LLM docs and endpoints
fix openai endpoints error - 400 - "invalid JSON"
=> multi-agent docs and endpoints update

docs/api-reference/endpoints/llm_agent.mdx, docs/api-reference/endpoints/multi_llm.mdx, docs/api-reference/openapi.yml, docs/docs.json, docs/getting-started/architecture.mdx, docs/getting-started/configuration.mdx, docs/getting-started/get-started.mdx, docs/getting-started/raspberrypi.mdx, docs/home.mdx, docs/robotics/coinbase-x402.mdx, docs/robotics/turtlebot4_zenoh.mdx
update x402 doc, and refine tb4 docs
=> X402 docs update

config/multiagent.json5, config/rag_multiagent.json5, src/llm/__init__.py, src/llm/plugins/multi_llm.py, src/llm/plugins/rag_multi_llm.py
This PR adds Retrieval-Augmented Generation (RAG) functionality to the OM1:
- Created a new `RagMultiLLM` class that extends the existing LLM functionality with RAG capabilities
- Added a dedicated configuration file `rag_multiagent.json5` for RAG-enabled multi-agent setup
- Enhanced the LLM configuration to include a `use_rag` flag
- Implemented proper knowledge base context retrieval and integration into agent prompts
- Added support for displaying tools used in knowledge retrieval
- Improved error handling and logging for RAG operations
The implementation now properly extracts voice input, queries the knowledge base, and integrates the retrieved context into the agent's reasoning process.
=> RAG Deploy 

src/inputs/plugins/vlm_coco_local.py, tests/inputs/plugins/test_vlm_coco_local.py
Fix method signature from PIL.Image to np array. Add unit test 
Added unit tests. `uv run src/run.py spot` works fine.
=> Fix coco local vlm method signature and add unit tests

src/llm/__init__.py, src/llm/plugins/rag_multi_llm.py, tests/llm/test_init.py
Replace BaseModel with dataclass in LLMConfig
This avoids adding more and more variables to LLMConfig
=> Add extra_params to LLMConfig

config/open_ai.json5, src/providers/unitree_realsense_dev_vlm_provider.py, src/providers/vlm_gemini_provider.py, src/providers/vlm_openai_provider.py, src/providers/vlm_vila_gazebo_provider.py
Fix https://github.com/OpenmindAGI/OM1/issues/245
**Verification**
running `uv run src/run.py open_ai` works as expected
=> Fix VLM provider VideoStream register_frame_callback

docs/api-reference/endpoints/account_balance.mdx, docs/api-reference/endpoints/create_api_keys.mdx, docs/api-reference/endpoints/delete_api_keys.mdx, docs/api-reference/endpoints/list_api_keys.mdx, docs/api-reference/openapi.yml, docs/docs.json, tests/providers/test_sleep_ticker_provider.py
=> Add API key docs

src/actions/move_go2_autonomy/connector/unitree_sdk.py, src/providers/odom_provider.py, src/providers/rplidar_provider.py
Use RPLidarProvider as the central component for generating possible movement options. Other components can read them directly from RPLidarProvider.
=> Generate movement path in rplidar provider

src/backgrounds/plugins/rf_mapper.py, src/providers/fabric_map_provider.py, uv.lock
=> Update RF data type

config/test_lidar.json5, config/turtlebot4.json5, config/turtlebot4_lidar.json5, config/turtlebot4_lidar_gps.json5, config/unitree_go2_autonomy.json5, config/unitree_go2_mapper.json5, docs/robotics/motion_planning_lidarA1M8.mdx, src/backgrounds/plugins/rf_mapper.py, src/backgrounds/plugins/rplidar.py, src/inputs/plugins/rplidar.py, src/providers/rplidar_provider.py, system_hw_test/rptest.py
=> add min parameter for lidar

.gitignore, src/actions/move_go2_autonomy/connector/unitree_sdk.py, src/llm/__init__.py, src/llm/plugins/openai_llm.py, src/providers/rplidar_provider.py, src/run.py, src/runtime/logging.py, system_hw_test/rptest.py, tests/providers/test_unitree_camera_vlm_provider.py
- Fix the lidar crash issue
- Add a option to write logs to a logging file `--log-to-file`
- Remove `StopMove` to avoid the timeout issue
- Add `timeout` to LLM
=> Fix lidar crash and add logging option

config/test_ble_gps.json5, docs/robotics/gps_compass.mdx, src/inputs/plugins/gps.py, src/providers/fabric_map_provider.py, src/providers/gps_provider.py
=> bits-specific configuration

docs/development/intro.mdx, src/providers/rplidar_provider.py, src/providers/unitree_go2_state_provider.py, src/run.py, src/runtime/logging.py
Improve logging system to use the same config for the mp processes
=> Improve logging for mp processes

src/actions/move_game_controller/connector/go2_game_controller.py, src/actions/move_go2_autonomy/connector/unitree_sdk.py, src/backgrounds/plugins/odom.py, src/backgrounds/plugins/rf_mapper.py, src/inputs/plugins/gps_odom_reader.py, src/inputs/plugins/odom.py, src/providers/odom_provider.py, src/providers/unitree_go2_state_provider.py, src/runtime/config.py
This can stabilize the odom reader.
=> Move Odom channel reading to mp

src/actions/move_game_controller/connector/go2_game_controller.py
This allows users to do the long pressing of the buttons
=> Allow the long pressing of buttons

src/providers/odom_provider.py
Report the timestamp with the odometry data
=> Report timestamp with odom

config/spot.json5, config/ubtech_yanshee.json5, docs/developing/1_get-started.mdx, docs/robotics/ubtech_yanshee.mdx, mintlify/developing/1_get-started.mdx, mintlify/docs.json, mintlify/mintlify_splash.mdx, mintlify/robotics/ubtech_yanshee.mdx, src/actions/emotion/interface.py, src/actions/face/interface.py, src/actions/move/interface.py, src/actions/speak/interface.py, src/runtime/config.py
=> added ubtech setup docs

docs/api-reference/introduction.mdx, docs/examples/overview.mdx, mintlify/api-reference/introduction.mdx, mintlify/developing/1_get-started.mdx, mintlify/examples/overview.mdx, mintlify/robotics/coinbase_hackathon.mdx
mintlify sync, broken link fix, api docs updated
=> fix broken links and sync mintlify

.github/workflows/release.yml, Dockerfile, docker-compose.yml
updated credential and introduced volume for virtual env
=> Docker image fix

config/unitree_g1_humanoid.json5, src/actions/arm_g1/connector/unitree_sdk.py, src/actions/arm_g1/interface.py, src/actions/move_go2_autonomy/connector/unitree_sdk_advance.py, src/inputs/plugins/simple_paths.py, src/providers/d435_provider.py, src/providers/simple_paths_provider.py, src/providers/unitree_go2_state_provider.py, src/runtime/cortex.py, src/zenoh_idl/sensor_msgs.py, system_hw_test/intel435_obstacle_zenoh.py, system_hw_test/simple_paths.py
=> Add g1 autonomy

.github/workflows/release.yml
Fix release version for docker image
=> Fix release version

config/unitree_go2_autonomy_advance.json5, docker-compose.yml, src/actions/face/connector/avatar.py, src/backgrounds/plugins/avatar.py, src/providers/avatar_provider.py
Add avatar background server to communicate with the OM1-avatar
=> Add avatar server

docker-compose.yml, pyproject.toml, src/inputs/plugins/vlm_gemini.py, src/inputs/plugins/vlm_openai.py, src/inputs/plugins/vlm_vila.py, src/providers/vlm_gemini_provider.py, src/providers/vlm_openai_provider.py, src/providers/vlm_vila_provider.py, tests/providers/test_vlm_gemini_provider.py, tests/providers/test_vlm_openai_provider.py, tests/providers/test_vlm_vila_provider.py, uv.lock
Fix docker volume for the config folder
=> Fix volume

docker-compose.yml, src/providers/unitree_go2_location_provider.py
Add the location volume to sync with OM ROS2 SDK.
=> Add location volume

docs/full_autonomy_guidelines/om.mdx, mintlify/full_autonomy_guidelines/om.mdx
Updated the audio config docs for supporting noise cancellation and the echo reduction
=> updated docs for audio config
